### PR TITLE
Updated dependencies and removed superfluous nil from logs

### PR DESCRIPTION
**Pull request by hexpunk**

### CODE REVIEW

**Comment by nberger** [comment]
Thanks for the PR!

I have just 1 comment for now: I'd like to try and keep the clojure dependency on 1.6 while making it sure that the library is compatible with newer versions so I'd be happy to run the tests on newer versions instead of updating to 1.8. I just pushed a change in ring-logger doing exactly that (I had the change ready for a while and this made me to push it, so also thanks for the pressure :) ). If you could send a separate PR doing smth similar as in https://github.com/nberger/ring-logger/pull/23 and to not update the clojure version here, that would be great!

**Comment by hexpunk** [comment]
How about now? :-)

**Comment by nberger** [comment]
The change looks good. It'd be great if you could split the multiple clojure versions part into a separate PR. You'd need to do some rebase, please let me know if you are not familiar with that.

**Comment by hexpunk** [comment]
I can do that.  I'll close this PR for now.  Give me a few minutes to put up the two new ones.

**Pull request closed without merging**
