### PR TITLE
Only log throwable when it's not nil

### PR DESCRIPTION
**Pull request by hexpunk**

### CODE REVIEW

**Comment by nberger** [comment]
Giving a second thought to this and looking through timbre code, I now think that we should be able to pass `nil` as `throwable` and timbre (+ appenders being used) should handle it well. Are you using any specific appender, or just the default ones? Could you please post an example log line that includes this `nil` throwable?

A few references from timbre that seem related to this: https://github.com/ptaoussanis/timbre/blob/22603b5134/src/taoensso/timbre.cljx#L85 (`throwable` ends as `:?err` which is "First-arg platform error, or nil") and https://github.com/ptaoussanis/timbre/pull/216 (a PR fixing what sounds like the same issue with the cljs console appender)

**Comment by hexpunk** [comment]
I'm not using any custom appenders at the moment.  My code looks like this:

```clojure
(def handler
  (-> (compojure/routes
        (GET "/api/ping" [] ping-handler)
        (route/not-found "No such page."))
      (wrap-params)
      (wrap-with-logger)
      (wrap-cors :access-control-allow-origin #".*"
                 :access-control-allow-methods [:get :put :post :delete])))
```

And the resulting logs look like this:

```
17-06-30 17:13:43 machine-name INFO [example.core:37] - server started at http://127.0.0.1:8080
17-06-30 17:13:50 machine-name INFO [ring.logger.timbre:10] - nil Starting :get /api/ping for 0:0:0:0:0:0:0:1 {"host" "localhost:8080", "user-agent" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWeb
Kit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36", "cookie" "[REDACTED]", "connection" "keep-alive", "upgrade-insecure-requests" "1", "accept" "text/html,application/xhtml+xml,application/xml;q=0
.9,image/webp,image/apng,*/*;q=0.8", "accept-language" "en-US,en;q=0.8", "accept-encoding" "gzip, deflate, br", "dnt" "1"}
17-06-30 17:13:50 machine-name DEBUG [ring.logger.timbre:10] - nil Request details: {:query-string nil, :remote-addr "0:0:0:0:0:0:0:1", :request-method :get, :scheme :http, :server-name "localhost", :server
-port 8080, :uri "/api/ping"}
17-06-30 17:13:50 machine-name TRACE [ring.logger.timbre:10] - nil [ring] Sending response: {:status 200, :headers {"content-type" "application/json"}, :body "{\"ping\":\"pong\"}"}
17-06-30 17:13:50 machine-name INFO [ring.logger.timbre:10] - nil Finished :get /api/ping for 0:0:0:0:0:0:0:1 in (21 ms) Status: 200
```

You can see the bothersome `nil` appearing before "Starting" and "Finished".

**Comment by hexpunk** [comment]
I just looked through the code for timbre's default appender in Clojure.  Looks like it doesn't support `:?err`.

I opened https://github.com/ptaoussanis/timbre/issues/235 to ask if that's intentional in timbre.

**Comment by nberger** [comment]
@JayAndCatchFire: thanks for the example log output and for the issue created in timbre. Hopefully somebody with more knowledge on timbre will help us there.

I added an example project using ring-logger-timbre under the `example` directory in this repo (it's basically the same example as in ring-logger). What's interesting from running it is that on the current release (`0.7.5`) it doesn't log that cumbersome `nil`. But running it on current master it does log the `nil` as you are reporting here.

Before moving on with this PR I'd like one of these two things to happen:

1. To know exactly which version/commit of timbre introduced this behavior to add that information in the timbre ticket and verify that there's not going to be a fix in timbre soon.
2. Add a test here that reproduces this behavior to avoid future regressions.

(you can run the example on current master by doing a `lein install` in the ring-logger-timbre directory, switching the example to use `ring-logger-timbre "0.7.6-SNAPSHOT"` and then doing a `lein run`)

(it seems like on "0.7.5" there's a whitespace instead of the `nil` in the log output, but I'd say that's less cumbersome than the `nil`)

**Comment by nberger** [comment]
Merging this to release it as `0.7.6`. I'll add some tests later. Thanks for contributing!

**Pull request merged**
